### ISSUE TITLE
Why exclude markup from name?

### ISSUE THREAD

**Issue by r12a** [w3c/activitystreams#338]
Please Indicate One: 
- [ ] Editorial
- [x] Question
- [ ] Feedback
- [ ] Blocking Issue
- [ ] Non-Blocking Issue

[This issue has support from others in the i18n WG.]

https://www.w3.org/TR/activitystreams-vocabulary/#dfn-name

> HTML markup MUST NOT be included.

What is the reason for explicitly excluding markup from the name value, whereas it is allowed for other natural language values?  It will force people to convert to or use control characters for inline bidirectional controls, and will prevent inline annotation for language change. Why cannot implementations simply remove markup (and convert bidi markup to control codes where needed)?

**Comment by jasnell** [comment]
Activity Streams documents have been typically used in a broad range of applications, with information often being displayed in locations where markup is not processed. The `name` property is intended to provide a simple markup-free label that can be used and displayed as-is with a minimal amount of processing. The `title` property is provided as an alternative to `name` when the use of markup is desired.

Also note that this is a carryover from Activity Streams 1.0 where the field was originally named `displayName`

**Comment by r12a** [comment]
I don't see a definition for the `title` property at https://www.w3.org/TR/activitystreams-vocabulary/.  I was under the impression that it had been removed(?)

**Comment by jasnell** [comment]
Sorry, completely forgot that title was removed. Summary can be used as an
alternative.

**Comment by evanp** [comment]
So, I think that the AS community has come to depend on a markup-free `name` property, and it would be difficult to retool for this kind of change.

I'm going to close this issue, but it's waiting for the commenter to see if using the `summary` as an alternative is acceptable.

**Comment by sandhawke** [comment]
(We should give @r12a a chance to close the issue himself.     We once decided that was more polite.)

**Comment by r12a** [comment]
Thank you.  I agree that it's more polite ;-), but more importantly it signals to others who are following the issue (eg. people from www-international community) that the resolution isn't yet agreed, so they should still pay attention.  I'm about to summarise the current status of these issues with a view to discussing during our Thursday telecon, so we can give feedback, so look out for that soon hopefully.

**Comment by evanp** [comment]
@r12a let us know when you've got an answer.

**Comment by r12a** [comment]
It seems like `name` is a particularly frequently used property. I hear what you're saying about some existing applications being unable to handle things other than plain text.  What i'm concerned about is that if we don't provide a way for applications to do better we'll always have this problem.  I'm wondering what could be done to encourage applications to move away from this behaviour or find a way for them to at least not prevent better applications from doing the right thing.

I guess i'm not totally clear about the role of the `summary` property. It was pointed out that one can put markup in that.  Is it equivalent to the name property in terms of usage? Would an application that knows how to deal with markup take that value rather than the `name` value for the same use?  Would it make sense to add advice to the spec to say, if you can benefit from using markup then use both the `name` and `summary` properties with the same content except that one has markup and the other not?

**Comment by evanp** [comment]
So, I think my main concern here is that to enable two particular uses (direction markup and change of language within a `name`) we'd be requiring implementations to render completely the entire variety of markup that could be put into that `name`. Sanitizing, parsing, and rendering HTML is a big job, and it is a big requirement to put onto implementers!

I'd point to the example of avoiding [https://www.w3.org/Provider/Style/TITLE.html](structural markup in the HTML title element), or the mechanism for using [https://tools.ietf.org/html/rfc4287#section-4.2.14](plain-text titles in Atom) (whence, I think, this particular requirement for AS2 comes from originally).

I'd really like to keep us to a no-markup version of `name`. What can we do to make this work?

**Comment by BigBlueHat** [comment]
Saw mention of [Web Annotation's `direction` property](https://www.w3.org/TR/annotation-vocab/#direction) and wondered if something like this might work for @r12a (who [helped us make that conclusion](https://github.com/w3c/web-annotation/issues/224) fwiw). :smile: 

#### Proposal
 - add the `oa:direction` property (and `oa:ltr`/`oa:rtl` values) to AS2's vocab
 - have it be considered the default direction for `name`, `summary`, and `content`
 - keep `name` as a string (no markup)
 - use `mediaType` for both `summary` and `content`
 - support `directionMap` when various languages are in use

Maybe not perfect, but hopefully helpful. :smile:

**Comment by akuckartz** [comment]
That relation between `name` and `summary` is not indicated by the property names. Something like `nameWithMarkup` would be a more telling name.

**Comment by BigBlueHat** [comment]
@akuckartz cute. :wink: 

I think their origin comes from [`atom:name`](https://tools.ietf.org/html/rfc4287#section-3.2.1) and [`atom:summary`](https://tools.ietf.org/html/rfc4287#section-4.2.13)

In Atom's case, this was the reasoning:
> It is advisable that each atom:entry element contain a non-empty atom:title element, a non-empty atom:content element when that element is present, and a non-empty atom:summary element when the entry contains no atom:content element.

From the AS2 vocab descriptions, the intended usage seems to match.

**Comment by r12a** [comment]
I don't think that a `direction` property is relevant here, since the question is about how inline markup could help in managing inline changes in styling and semantics,  including language and direction.

In the case of text direction, it is possible to use Unicode control characters where necessary, although this is an approach people who speak languages based on RTL scripts dislike and find more difficult to use than markup.  For labelling inline language changes, there is no alternative to markup that i'm aware of (although it could be argued that the failure to identify such inline changes is rarer and less problematic than for direction, it's still a shame not to be able to do that when needed).

The relationship between `name` and `summary` is still not clear to me. I believe the spec says that `name` is always a required property, which seems to answer the original question i had about whether they are alternatives (the answer being no).  (I'm still wondering in what circumstances the `summary` property should be used.) 

It seems that the Social Web WG probably won't change `name` to allow it to use markup.  If that's the case, then i think we should add a note to the spec to say the WG is aware that `name` can sometimes present difficulties for some international users due to it being plain text only.  

(@evanp, as an aside, the `title` attribute has been a bugbear for a long time - in XHTML2 they actually made it support markup, but of course that was eclipsed by HTML5 - as are other uses of plain text. I wish we could somehow find a way to reverse that trend. At least i'd like to make people aware of the consequences.)

**Comment by tantek** [comment]
@r12a you wrote:
"(@evanp, as an aside, the title attribute has been a bugbear for a long time - in XHTML2 they actually made it support markup, but of course that was eclipsed by HTML5"

This empirical example illustrates two very important points:

1. **Aspirational approaches fail** (like XHTML2 adding markup to the title attribute, nearly all of XHTML2 for that matter) Aspirational approaches (publish a spec first, prototype later/never) have an exceptionally bad track record of actually "working" (being implemented, adopted etc.), and thus any requirements they are designed for (no matter how idealistic / helpful), are rarely or more likely never actually satisfied in practice. This is why we ask for prior **successful** examples (implemented, adopted by users for whom the requirements matter, etc.) of any particular technique or approach, and why W3C as a whole is moving towards a model of incubating in CGs, and only when techniques have been prototyped, taking them to WGs. Not universally adopted yet, but as an org we are moving efforts as a whole in this direction.

2. **Even HTML has never solved these problems** In addition to the title attribute case, I brought up a similar example on our SWWG teleconference 2016-07-26: http://socialwg.indiewebcamp.com/irc/social/2016-07-26#t1469555251308

The &lt;title&gt; **element** in HTML also does NOT support markup, and frankly has a very similar semantic as the "name" in AS2.

We also have the counter-example of Atom's entry:title element, which did in theory support markup, but in practice, support for such nested markup was never widely implemented, certainly not interoperably, and thus in practice, that "feature" of "markup inside title" was broken and unusable. The approach just didn't work.


@r12a also wrote "as are other uses of plain text. I wish we could somehow find a way to reverse that trend. At least i'd like to make people aware of the consequences.)"

This gets to the heart of the issue.

Formats use plain text "strings" to represent user visible content EVERYWHERE.

This is not just a SWWG technology thing, or even a W3C technology thing. This is a global computing platforms kind of thing, across all programming languages, frameworks, operating systems.

Nearly all existing and in-development formats and protocols that have any kind of structured information, where some of that information is human visible text, use "just" strings for that text, without embedded markup, without per-string sideband properties for dir/lang etc. (HTML elements being an exception).

E.g. 
1. vCard's "fn", "org", "note" etc. properties. 
* Any JSON API/format/protocol from any website, from small regional websites, to global sites (Twitter, Facebook, Google) supporting millions of users in numerous languages (LTR, RTL etc.). 
* Even W3C attempts like in App Manifest: https://www.w3.org/TR/appmanifest/#dir-member
Have dir/lang sideband properties that apply *globally* to all properties in the JSON, not allowing anything per property, certainly no nested markup in string properties. And what's worse, there's no evidence here of actual support even of this minimal attempt at global dir/lang sideband properties in JSON.
 * Any test cases for the algorithm(s) described at the above link? 
 * Any implementations claiming to pass those? (implementation reports? browsers we can view test cases in that demonstrate passing vs. not?)


Satisfying the string/text requirements as communicated by i18n, in the context of JSON (or any non-HTML) formats, is an unsolved problem in practice.

This is not unique to the SWWG's specs or technologies, thus it is unreasonable (and ineffective) to place that burden on the SWWG (or any other particular WG and their specs).

@r12a your expression in particular: "I wish we could somehow find a way to reverse that trend" really makes it clear where we are. 

We are in the "I wish" phase of coming up with a solution, and thus attempting to lead with a specification first (instead of working prototype) is a theoretical, aspirational approach, with little or no chance of success, of actually helping the quoted millions of users you are trying to help.

A better approach here would be for the i18n group to try to prototype a variety of approaches to solving this problem (or trying to solve it "upstream" with Unicode, so that UTF8 strings "just work" everywhere that strings are used), and when there are prototypes that show promise, we can iterate on them.

Until then, unproven (unimplemented?) techniques like the properties added to Annotations specs, or App Manifest, only provide the **appearance** of solving a problem, which in some ways is **worse** than doing nothing, because not only have you not solved the problem(s) for the people you are trying to help, you have **delayed** working on an actual workable solution, while waiting for the aspirational/theoretical solution to take years to fail in practice (just like nested markup in Atom's entry:title element, which took many years to demonstrate failure in practice).

@r12a wrote: "At least i'd like to make people aware of the consequences."

I think this is where the focus needs to be today.

In particular by the i18n group analyzing existing widely globally deployed and in-use JSON APIs/formats, proprietary or not, especially those deployed (and adopted!) by RTL language users like the aforementioned Twitter, Facebook, Google, etc. global platforms. And either:
* Document what techniques they used to solve the i18n requirements (thus providing market-proven building blocks for W3C and others to use).
* OR document the struggles ("consequences") that users with those requirements are having with those global platforms, and specifically WHY and HOW those users do apparently still use those global platforms despite those struggles.
* OR a mix of those two, what requirements they have solved with actual adopted solutions, and what requirements have they not yet solved, and why/how is it that those users are still using those platforms despite those unaddressed "requirements".

**Comment by kevinmarks** [comment]
There was a unicode spec for tagging language inline:
https://tools.ietf.org/html/rfc2482
But this was deprecated:
https://tools.ietf.org/html/rfc6082

However, this could change, as unicode 8 reopened that character block. If expressing language in text is needed, working with the unicode consortium to revive this may be a useful direction.

**Comment by BigBlueHat** [comment]
Given that this is a new spec and that old `text/plain` values can be stored `text/html` supporting fields, there's no technical reason why `name` and `summary` couldn't support markup.

I'll also note that the most recent JSON definition [RFC7159](http://rfc7159.net/rfc7159) states the following in the ["String and Character Issues" section](http://rfc7159.net/rfc7159#rfc.section.8):
> Implementations MUST NOT add a byte order mark to the beginning of a JSON text. In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

**Comment by kevinmarks** [comment]
Putting a BOM in utf8 was always wrong. It was only ever done to placate
Microsoft's buggy encoding sniffing code based on some legacy '16 bits
should be enough for anyone' approach to unicode.

**Comment by jasnell** [comment]
@BigBlueHat the key challenge with allowing `name` to contain markup is that it is intended to be a reliably *readable* label for the object. By allowing markup, we allow things like `"name": "<img src=\"title.jpg\"/>"`, which would be legal but completely useless for the intended purpose. We need to make sure that if markup is permitted, the value can still reasonably be handled as readable text.

**Comment by BigBlueHat** [comment]
@kevinmarks then storing the default `direction` seems prudent--given RFC7159 and knowing the language of the text are generally insufficient.

@jasnell good reasons. Thanks.

**Comment by r12a** [comment]
> However, this could change, as unicode 8 reopened that character block. If expressing language in text is needed, working with the unicode consortium to revive this may be a useful direction.

@kevinmarks I wouldn't hold your breath on that. The Unicode Standard not only deprecates it, but also strongly discourages it, and even says it twice in close succession:

> The use of tag characters to convey language tags is strongly discouraged.
> Tag identifiers
> E0001
> 
> LANGUAGE TAG
> • This character is deprecated, and its use is strongly discouraged.

**Comment by jasnell** [comment]
Language codes in text have a long rough history. As far as I can recall, there are several reasons why they were deprecated, not the least of which is that they tend to fail at capturing the rich complexity of [language tags](https://tools.ietf.org/html/bcp47) without adding significant complexity to the data. Also, unlike directionality, language is not really a property of the text itself. For instance, what language would I use to write a sentence that contains 40% arabic characters and 60% latin characters? It depends entirely on the context of how those are structured and the context in which it is used. Simply using glyphs from other writing systems in a string of text does not carry any language implications at all. Directionality, on the other hand, is fundamentally a property of the [glyphs themselves](http://userguide.icu-project.org/strings/properties).

**Comment by kevinmarks** [comment]
I would like to learn why they were deprecated, but they seem to have had a
start/end language run model, which would enable that case. In practice,
language tags in html aren't used much either,  and processors guess
language from the character sequences. Sadly, this often does have a
default monolingual assumption built in.

**Comment by evanp** [comment]
Closed per discussion of socialwg and as closed in w3c/i18n-activity#178
