### ISSUE TITLE
**Map fields become a SHOULD

### ISSUE THREAD

**Issue by evanp** [w3c/activitystreams#341]
@jasnell inserted text making the use of **Map properties RECOMMENDED over the default properties. I think this is unnecessarily complex, since I believe that most documents will be unilingual, and won't need different languages for each property.

**Comment by sandhawke** [comment]
But even if the languages uses all one language, how is one to know what that language is?

**Comment by evanp** [comment]
@sandhawke as mentioned in the spec, `@context` can have a `@language` property.

**Comment by sandhawke** [comment]
Oh, good, sorry I missed/forgot that.

**Comment by sandhawke** [comment]
I've added the i18n label, @r12a.  I hope that's right, procedurally.   Also, this is coming out of #335

**Comment by r12a** [comment]
As Sandro says, indeed the point of https://github.com/w3c/activitystreams/issues/335 was that, if a `summary`, say, is available only in a single language you still need to know what that language is to make the activity stream work in a worldwide Web.  

I believe the spec needs to be clear about how one would specify language for properties that have content in a single language, and in its examples show that identifying the language is a practice that should be followed by default.

(Not sure why this is raised as a separate issue, rather than continuing the discussion under https://github.com/w3c/activitystreams/issues/335)

**Comment by aphillips** [comment]
Piling on: the reason this was requested was because the default format doesn't (or at least didn't) include language information. Monolingual documents still need language and direction metadata. If that's been added in `@context`, that would help address the need expressed by this Issue.

**Comment by sandhawke** [comment]
In our telecon just now, we had rough consensus on saying

* if document producers know the language, they MUST include it in either *map properties or an @language nested in the @context

* if document consumers can use language information, they MUST look for it in *map properties and @language nest in the @context

Hopefully @evanp  will draft that in spec language.     The main counter-argument is that it raises the complexity of minimal implementations and minimal examples, but the sense in the telecon seemed to be that it was worth it.

BTW @jasnell is away this week and we'd like his confirmation before proceeding

**Comment by aphillips** [comment]
@sandhawke Cool. Thanks for the update. 

Did this consensus also include `@dir` information? Or is base direction (for RTL language support) being considered separately?

**Comment by evanp** [comment]
This was done as a different issue because we had already called out the use of the JSON-LD feature, `@language`, and that's not controversial.

What *is* controversial is having both the `@language` in the `@context` **and** making use of the **Map properties RECOMMENDED even if there is only one language version of the document. That would leave us with the complicated version of the document below:

```json
{
  "@context": {
    "@vocab": "http://www.w3.org/ns/activitystreams",
    "@language": "en"
  },
  "type": "Note",
  "nameMap": {
    "en": "A simple note"
  },
  "summaryMap": {
    "en": "This is the summary of the simple note."
  },
  "contentMap": {
    "en": "This is the content of the simple note."
  }
}
```

I think we can get along with just using the JSON-LD version of `@context`, which we specifically call out in the document, and which we use for other parts of the specification (like extensions). So if we don't make the *Map version of properties RECOMMENDED, we'd have a more tractable document like this:

```json
{
  "@context": {
    "@vocab": "http://www.w3.org/ns/activitystreams",
    "@language": "en"
  },
  "type": "Note",
  "name": "A simple note",
  "summary": "This is the summary of the simple note.",
  "content": "This is the content of the simple note."
}
```

It would still be possible to use the first version, of course; but the second version would be OK.

**Comment by evanp** [comment]
Another option would be to add a `language` or `defaultLanguage` property to our own vocabulary. I'm not keen on that, since it would replicated something already well-covered in JSON-LD.

I think we've already made using the `@context` property required for some functionality -- specifically, extensions -- and I think this is another good application.

**Comment by wilkie** [comment]
I think `@context` is just something that needs to be visible in all examples and should be in all activitystreams objects. Then it is no longer a stretch of the imagination to expect things to be in there. I believe `@language` inside `@context` will be less of a burden on implementations as long as the examples in the spec are clear enough that people must look for `nameMap` when `@language` is unknown. I can see people ignoring `nameMap` completely and some implementations may just decide to use only `nameMap` which is possible and maybe even practical. Nobody is going to use `name` and `nameMap` together, I would assume.

It would be nice if `name` could be a string that logically expands to an object using the default language or an object with language key/values instead of having both `name` and `nameMap` etc. oh well.

**Comment by evanp** [comment]
At this point, we're waiting for @jasnell to see if he can live with this formulation.

**Comment by aphillips** [comment]
@evanp I don't have a problem with what you suggest.

Note that `RECOMMENDED` doesn't make the simpler form non-conforming. It just says that you SHOULD use the map form. You could even make it lowercase recommended (i.e. something like a health warning that "Use of the map form is recommended when the language is different from that of the `@context` or when language information is associated with a specific value separately from the document as a whole.")

**Comment by evanp** [comment]
@sandhawke Also, I wonder if there's a fair comparison with [language-tagged strings](https://www.w3.org/TR/rdf11-concepts/#dfn-language-tagged-string) in RDF. Are they recommended even if the language of the document is declared elsewhere? Is it good style? I'm not sure.

**Comment by akuckartz** [comment]
JSON-LD is an RDF-serialisation. Language maps and `@language` are two different JSON-LD tools to express the same RDF language-tagged strings. In other words: If a JSON-LD document is converted to Turtle one does not know how (and if) these language-tagged strings were serialised in JSON-LD before.

**Comment by azaroth42** [comment]
Language as a property, rather than being part of the RDF model layer, was considered in #251.

**Comment by r12a** [comment]
How do the proposed solutions support the use case where the values of note, summary and content are in different languages, which seems entirely possible to me?  It seems you might have to add some html markup to the properties that are not in the default language, which is a little clunky if it's just to get around the inability to apply language metadata to individual properties, and seems especially problematic because the default language would always have to be that of the `name` property, since it doesn't accept html markup:

```
{
  "@context": {
    "@vocab": "http://www.w3.org/ns/activitystreams",
    "@language": "en"
  },
  "type": "Note",
  "name": "Richard added a new post to his wall",
  "summary": "Première phrase de Béowulf.",
  "content": "Hwæt wë Gār-Dene   in geārdagum, \ þēodcyninga    þrym gefrūnon, \ hū þā æþelinʒas   ellen fremedon."
}
```

**Comment by r12a** [comment]
Um. To finish off what i was saying before: So although you wouldn't want to in normal monolingual situations,  i would expect that it may make sense to allow a mixture of `@language` and `...Map` in this case, as follows:


```
{
  "@context": {
    "@vocab": "http://www.w3.org/ns/activitystreams",
    "@language": "en"
  },
  "type": "Note",
  "name": "Richard added a new post to his wall",
  "summaryMap": { "fr": "Première phrase de Béowulf." },
  "contentMap": { "ang": "Hwæt wë Gār-Dene   in geārdagum, \ þēodcyninga    þrym gefrūnon, \ hū þā æþelinʒas   ellen fremedon." }
}
```
In summary, 
* using `@language` in the context seems to be the most straightforward way to provide language information in a unilingual situation
* where properties are localised into multiple languages, then `...Map` should be used for all natural language text
* where one property is in a different language than others, use `@language` for the default language, and use `...Map` for properties containing values in other languages.

Does that make sense?

**Comment by jasnell** [comment]
I am back from my camping trip with the family but won't be catching up on
things until Monday. Even then I'm still technically on vacation for
another week. I'll get a response as soon as possible.

**Comment by evanp** [comment]
@r12a your second example looks correct. I'm mostly concerned with what I think is the base case: where all natural language properties are in the document's default language.

**Comment by evanp** [comment]
@jasnell it'd be great to get your response before tomorrow's telecon. I think that making the *Map properties RECOMMENDED even if we have a way to declare default language makes for clumsy documents (as seen above).

**Comment by jasnell** [comment]
I'd prefer not to make the Map properties recommended in general. In other
words, I agree with you

**Comment by evanp** [comment]
Awesome. Let's close this one, then.
