### ISSUE TITLE
Remove or move pre-PR text

### ISSUE THREAD

**Issue by evanp** [w3c/activitystreams#408]
This is text that is only applicable before PR. Here's what I think we have:

[ ] At Risk section
[ ] Exit criteria (@tantek suggests moving this to an appendix)
[ ] At Risk notes
[ ] Changelog

I'm not sure which of these should be removed. @sandhawke and @rhiaro any suggestions?

**Comment by sandhawke** [comment]
I think remove everything about At Risk (except in explaining what was removed, in the changelog)

Personally I'd remove Exit Criteria, because I don't think reading the PR will care, but whatever.

I'd do the changelog like you did in the CR draft, where it just has changes since the previous draft, but includes a convenient link to the that draft's changelog.  As we're getting more stable, it might also be nice to include a link to a color-coded diff (hosted on github, I guess) of the exact changes.   I like  https://github.com/cygri/htmldiff for this.

What's your timeline?   We probably need about 3 weekdays after you're ready before the actual publication date.

**Comment by tantek** [comment]
This makes sense to me. I have a slight preference for keeping the Exit Criteria, e.g. as an appendix or in-place as an existing non-normative section.

FWIW it appears we kept the exit criteria inline in Webmention PR as a non-normative section: https://www.w3.org/TR/2016/PR-webmention-20161101/#candidate-recommendation-exit-criteria but then dropped it from the REC: https://www.w3.org/TR/webmention/#conformance - not sure if either of those decisions (keep in PR, drop in REC) was deliberate, accidental, or editor's choice as to what seemed right.

**Comment by sandhawke** [comment]
Do you need anything more on this @evanp ?
