### ISSUE TITLE
Please clarify the RDF/OWL namespace URI

### ISSUE THREAD

**Issue by imitko** [w3c/activitystreams#529]
Please Indicate One: 
 * [] Editorial
 * [ ] Question
 * [x] Feedback
 * [ ] Blocking Issue
 * [x] Non-Blocking Issue

Please Describe the Issue:

In the [specification](https://www.w3.org/TR/activitystreams-core/) as well as in JSON-LD context document the namespace URI is `https://www.w3.org/ns/activitystreams#` whereas in [ontology](https://github.com/w3c/activitystreams/blob/master/vocabulary/activitystreams2.owl) is `http://www.w3.org/ns/activitystreams#` (note URI schema part). IMHO the RDF/OWL document do not match the URI used everywhere in specification. The clarification or fix is needed because transformation from JSON-LD to RDF currently do not match ontology.

Kind Regards,
Mitko

**Comment by csarven** [comment]
https://github.com/w3c/activitystreams/pull/504#issuecomment-823599673

**Comment by evanp** [comment]
There is an extended discussion of the OWL vocabulary in ticket #416 . I'm going to close this ticket in favour of that one.

The OWL ontology for Activity Streams 2.0 is non-normative and not well maintained. However, there are enough interested parties that care about using OWL that it probably makes sense to maintain this document on a best-effort basis.

I think for the question of https vs. http, because the vocabulary is non-normative, we should be able to make a change to https without too much concern about backwards compatibility. We made this change with JSON-LD about 5 years ago, so the equivalence between the two representations should be reasonable to achieve.
