### ISSUE TITLE
the orderedItems property mentioned in the Activity Streams 2.0 recommendation is not defined in the Activity Vocabulary 

### ISSUE THREAD

**Issue by cristianolongoodhl** [w3c/activitystreams#576]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [X] Non-Blocking Issue

Please Describe the Issue:

In https://www.w3.org/TR/activitystreams-core/#collections the orderedItems property is mentioned for representing ordered items of a collection. However I can't find this property in the [Activity Vocabulary](https://www.w3.org/TR/activitystreams-vocabulary/#properties) . I suggest to remove orderedItems as it is redundant with the items property of an OrderedCollection.  Notice that, this property occurs in several examples for the vocabulary.

**Comment by tesaguri** [comment]
Note that `orderedItems` is defined in the normative JSON-LD context document so that it's not something that has come out of thin air.

I think there is confusion between the terminologies [_property_][rdf11-concepts-dfn-property] and [_term_][json-ld11-dfn-term]. The difference is crucial here because `items` and `orderedItems` are two different JSON-LD _terms_ for the same RDF _property_ (`as:items`), but with different context definitions to give each of the terms different RDF semantics for the same JSON syntax (the JSON array syntax in this case).

The `items` term represents multiple RDF triples with each of the array values being their objects respectively. For example, `{"items": ["a", "b"]}` represents something like `[ as:items <a> , <b> ] .` in a pseudo-Turtle. On the other hand, the `orderedItems` term represents a single RDF triple with its object being an `rdf:List` resource. For example, `{"orderedItems": ["a", "b"]}` represents something like `[ as:items ( <a> <b> ) ] .`.

So it's true that there is no RDF property named `as:orderedItems` in Activity Vocabulary, and the Reconnendation's phrasing <q>`orderedItems` property</q> may be misleading. But I don't believe that the `orderedItems` is redundant since it has a semantics distinct from `items`.

See also #437.

[rdf11-concepts-dfn-property]: <https://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/#dfn-property>
[json-ld11-dfn-term]: <https://www.w3.org/TR/2020/REC-json-ld11-20200716/#dfn-term>

**Comment by nightpool** [comment]
Yes. The orderedItems property is a required part of the JSON-LD syntax for
the "items" vocabulary term when such items are ordered. it doesn't appear
in the RDF document because it's not a property in and of itself, just part
of the json ld syntax for representing the items property in certain cases

**Comment by cristianolongoodhl** [comment]
Thank you all, I think this issue can be considered a duplicate of #437

**Comment by cristianolongoodhl** [comment]
> Note that `orderedItems` is defined in the normative JSON-LD context document so that it's not something that has come out of thin air.

But the "context" is part of the ActivityPub specification and not of ActivityStream, am I right? May be the specifications stack and the order in which specifications have to be read is not really clear to me.

**Comment by tesaguri** [comment]
> But the "context" is part of the ActivityPub specification and not of ActivityStream, am I right? 

[Section 2.1][activitystreams-core-jsonld] of the Activity Streams Recommendation refers to the context as <q>normative</q>.

[activitystreams-core-jsonld]: <https://www.w3.org/TR/2017/REC-activitystreams-core-20170523/#jsonld>

**Comment by cristianolongoodhl** [comment]
Thank you very much, may I close this issue?

**Comment by nightpool** [comment]
Please do

**Comment by cristianolongoodhl** [comment]
Closed as duplicate of #437
